export const APPLICATION_LOADING_ERROR = 'APPLICATION_LOADING_ERROR';
export const APPLICATION_LOADING_SUCCESS = 'APPLICATION_LOADING_SUCCESS';
export const APPLICATION_LOADING_IN_PROGRESS = 'APPLICATION_LOADING_IN_PROGRESS';

export const AUTHENTICATION_PASSWORD_SET = 'AUTHENTICATION_PASSWORD_SET';

export const CHAIN_ID_SET = 'CHAIN_ID_SET';
export const SERVER_ID_SET = 'SERVER_ID_SET';
export const RPC_SERVER_ADDRESS_SET = 'RPC_SERVER_ADDRESS_SET';
