export const APPLICATION_LOADING_ERROR = 'APPLICATION_LOADING_ERROR';
export const APPLICATION_LOADING_SUCCESS = 'APPLICATION_LOADING_SUCCESS';
export const APPLICATION_LOADING_IN_PROGRESS = 'APPLICATION_LOADING_IN_PROGRESS';
export const AUTH_PASSWORD_SET = 'AUTH_PASSWORD_SET';
export const ACC_USERNAME_SET = 'ACC_USERNAME_SET';
export const ACC_PASSWORD_SET = 'ACC_PASSWORD_SET';
export const SEED_SET = 'ACC_SEED_SET';
