import { managerBaseURL } from './common';

export const SUBSCRIPTIONS_NODE_PROVIDER_ADD_IN_PROGRESS = 'SUBSCRIPTIONS_NODE_PROVIDER_ADD_IN_PROGRESS';
export const SUBSCRIPTIONS_NODE_PROVIDER_ADD_SUCCESS = 'SUBSCRIPTIONS_NODE_PROVIDER_ADD_SUCCESS';
export const SUBSCRIPTIONS_NODE_PROVIDER_ADD_ERROR = 'SUBSCRIPTIONS_NODE_PROVIDER_ADD_ERROR';

export const SUBSCRIPTIONS_NODE_PROVIDER_ADD_PARAMS_SET_PROVIDER_ADDRESS = 'SUBSCRIPTIONS_NODE_PROVIDER_ADD_PARAMS_SET_PROVIDER_ADDRESS';
export const SUBSCRIPTIONS_NODE_PROVIDER_ADD_PARAMS_SET_PLAN_ID = 'SUBSCRIPTIONS_NODE_PROVIDER_ADD_PARAMS_SET_PLAN_ID';

export const SUBSCRIPTIONS_NODE_PROVIDER_ADD_MODAL_SHOW = 'SUBSCRIPTIONS_NODE_PROVIDER_ADD_MODAL_SHOW';
export const SUBSCRIPTIONS_NODE_PROVIDER_ADD_MODAL_HIDE = 'SUBSCRIPTIONS_NODE_PROVIDER_ADD_MODAL_HIDE';

export const SUBSCRIPTIONS_INDIVIDUAL_HOST_ADD_IN_PROGRESS = 'SUBSCRIPTIONS_INDIVIDUAL_HOST_ADD_IN_PROGRESS';
export const SUBSCRIPTIONS_INDIVIDUAL_HOST_ADD_SUCCESS = 'SUBSCRIPTIONS_INDIVIDUAL_HOST_ADD_SUCCESS';
export const SUBSCRIPTIONS_INDIVIDUAL_HOST_ADD_ERROR = 'SUBSCRIPTIONS_INDIVIDUAL_HOST_ADD_ERROR';

export const SUBSCRIPTIONS_INDIVIDUAL_HOST_ADD_PARAMS_SET_NODE_ADDRESS = 'SUBSCRIPTIONS_INDIVIDUAL_HOST_ADD_PARAMS_SET_NODE_ADDRESS';

export const SUBSCRIPTIONS_INDIVIDUAL_HOST_ADD_MODAL_SHOW = 'SUBSCRIPTIONS_INDIVIDUAL_HOST_ADD_MODAL_SHOW';
export const SUBSCRIPTIONS_INDIVIDUAL_HOST_ADD_MODAL_HIDE = 'SUBSCRIPTIONS_INDIVIDUAL_HOST_ADD_MODAL_HIDE';

export const subscriptionsAddURL = (address) => {
    const baseURL = managerBaseURL();
    return `${baseURL}/accounts/${address}/subscriptions`;
};

export const SUBSCRIPTIONS_GET_IN_PROGRESS = 'SUBSCRIPTIONS_GET_IN_PROGRESS';
export const SUBSCRIPTIONS_GET_SUCCESS = 'SUBSCRIPTIONS_GET_SUCCESS';
export const SUBSCRIPTIONS_GET_ERROR = 'SUBSCRIPTIONS_GET_ERROR';

export const subscriptionsGetURL = (address) => {
    const baseURL = managerBaseURL();
    return `${baseURL}/accounts/${address}/subscriptions`;
};
