export const UI_DVPN_SET_SELECTED_TAB = 'UI_DVPN_SET_SELECTED_TAB';
export const UI_DVPN_TOGGLE_SHOW_SUBSCRIBED = 'UI_DVPN_TOGGLE_SHOW_SUBSCRIBED';
export const UI_DVPN_SET_SHOW_MAP = 'UI_DVPN_SET_SHOW_MAP';
